import { Suspense, lazy, useEffect, useRef, useState } from "react";
import { Loader2, MapPin, RefreshCw } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useReferenceCities, useReferences } from "@/lib/hooks/use-references";
import { useListing } from "@/lib/hooks/use-listings";
import { useEnrichNearby } from "@/lib/hooks/use-assets";
import { cn } from "@/lib/utils/cn";
import { formatDate } from "@/lib/utils/format";
import type { SectionDef, SectionDialogProps } from "../types";
import { Field, Row } from "../ui";

const LocationPicker = lazy(() =>
  import("@/components/shared/location-picker").then((m) => ({ default: m.LocationPicker })),
);

interface NominatimResult {
  place_id: number;
  display_name: string;
  lat: string;
  lon: string;
  address?: {
    road?: string;
    house_number?: string;
    suburb?: string;
    neighbourhood?: string;
    quarter?: string;
    village?: string;
    hamlet?: string;
    city?: string;
    city_district?: string;
    town?: string;
    county?: string;
    state_district?: string;
    state?: string;
    province?: string;
    region?: string;
    postcode?: string;
    country?: string;
    country_code?: string;
  };
}

// UX-254: Thai postal codes are 5 digits; the first 2 identify the province.
// We map the city → expected prefix so we can warn the host when Nominatim
// returns a postcode from the wrong province (the original bug returned
// 55520 / Phayao for a central-Chiang-Mai pin).
const CITY_POSTAL_PREFIX: Record<string, string> = {
  "Bangkok":     "10",
  "Chiang Mai":  "50",
  "Chiang Rai":  "57",
  "Phuket":      "83",
  "Pattaya":     "20",
  "Hua Hin":     "77",
  "Cha-am":      "76",
  "Koh Samui":   "84",
  "Krabi":       "81",
};

interface AddressParts {
  street: string;
  soi: string;
  subdistrict: string;
  district: string;
  province: string;
  postcode: string;
}

// Map Nominatim's address payload to our structured Thai address shape.
// Nominatim is messy here — different POIs return different sub-keys — so
// we try several fallbacks and keep the Soi separate when the road name
// itself contains "Soi" (common in Bangkok / CM addressing).
function parseNominatim(a: NominatimResult["address"] | undefined): AddressParts {
  if (!a) return { street: "", soi: "", subdistrict: "", district: "", province: "", postcode: "" };
  let road = (a.road ?? "").trim();
  let soi = "";
  // Split "Foo Road Soi 5" → road="Foo Road", soi="Soi 5"
  const soiMatch = road.match(/\b(Soi\s+\S+.*)$/i);
  if (soiMatch) {
    soi = soiMatch[1].trim();
    road = road.slice(0, road.length - soiMatch[1].length).trim();
  }
  const houseNum = a.house_number ? `${a.house_number} ` : "";
  return {
    street:      (houseNum + road).trim(),
    soi,
    subdistrict: a.suburb ?? a.neighbourhood ?? a.quarter ?? a.village ?? a.hamlet ?? "",
    district:    a.city_district ?? a.county ?? a.state_district ?? a.city ?? a.town ?? "",
    province:    a.province ?? a.state ?? a.region ?? "",
    postcode:    a.postcode ?? "",
  } as AddressParts;
}

function composeLegalAddress(parts: {
  unitNumber?: string;
  street?: string;
  soi?: string;
  subdistrict?: string;
  district?: string;
  province?: string;
  postcode?: string;
}): string {
  // BUG-364: drop case-insensitive duplicates so a Road and Soi that ended up
  // holding the same value (e.g. reverse-geocode put "Soi Jumpee" in both)
  // don't render as "Soi Jumpee, Soi Jumpee" on the contract / tenant address.
  const seen = new Set<string>();
  const headParts = [parts.unitNumber, parts.street, parts.soi]
    .map((s) => (s ?? "").trim())
    .filter(Boolean)
    .filter((s) => {
      const k = s.toLowerCase();
      if (seen.has(k)) return false;
      seen.add(k);
      return true;
    });
  const head = headParts.join(", ");
  const tail = [parts.subdistrict, parts.district, parts.province, parts.postcode]
    .map((s) => (s ?? "").trim())
    .filter(Boolean)
    .join(", ");
  return [head, tail].filter(Boolean).join(", ");
}

// Build a legal-address parts payload from the current draft, with a single
// field override. Lets the section's inputs cheaply recompute the
// autogenerated legal line without 8-line inline object literals.
function legalPartsFor(draft: { unitNumber: string; street: string; soi: string; subdistrict: string; district: string; province: string; zipCode: string }, override: Partial<{ unitNumber: string; street: string; soi: string; subdistrict: string; district: string; province: string; postcode: string }> = {}): Parameters<typeof composeLegalAddress>[0] {
  return {
    unitNumber:  override.unitNumber  ?? draft.unitNumber,
    street:      override.street      ?? draft.street,
    soi:         override.soi         ?? draft.soi,
    subdistrict: override.subdistrict ?? draft.subdistrict,
    district:    override.district    ?? draft.district,
    province:    override.province    ?? draft.province,
    postcode:    override.postcode    ?? draft.zipCode,
  };
}

// Roughly ±0.5° box around the city centre. Nominatim's `viewbox` + `bounded=1`
// means results outside the city are filtered out — so typing "Sukhumvit"
// while city = Bangkok won't return matches in other countries.
const CITY_RADIUS = 0.5;

function NearbyStatus({ listingId, assetId }: { listingId: string; assetId: string }) {
  const { data: listing } = useListing(listingId);
  const { mutate: refresh, isPending } = useEnrichNearby(assetId);

  const transit = listing?.transportInfo?.split(" · ").filter(Boolean) ?? [];
  const nearby = listing?.nearbyPlaces?.split(" · ").filter(Boolean) ?? [];
  const enrichedAt = listing?.nearbyEnrichedAt;
  const hasData = transit.length > 0 || nearby.length > 0;

  // Auto-trigger on first open if location is set but no enrichment has run yet.
  useEffect(() => {
    if (hasData || enrichedAt || isPending) return;
    refresh();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [assetId]);

  return (
    <div className="mt-2 rounded-xl border border-border bg-bg-subtle p-4 space-y-3">
      <div className="flex items-center justify-between gap-2">
        <div className="flex items-center gap-2 text-sm font-medium text-fg">
          <MapPin size={14} className="shrink-0" />
          <span>Nearby places</span>
          {enrichedAt && (
            <span className="text-xs font-normal text-fg-muted">· {formatDate(enrichedAt)}</span>
          )}
        </div>
        <Button
          type="button"
          variant="ghost"
          size="sm"
          className="h-7 px-2 text-xs shrink-0"
          onClick={() => refresh()}
          disabled={isPending}
        >
          <RefreshCw size={12} className={cn("mr-1", isPending && "animate-spin")} />
          Refresh
        </Button>
      </div>

      {hasData ? (
        <div className="space-y-2">
          {transit.length > 0 && (
            <div className="flex flex-wrap gap-1.5">
              {transit.slice(0, 5).map((t) => (
                <span
                  key={t}
                  className="inline-flex items-center gap-1 rounded-full border border-border bg-bg-card px-2.5 py-1 text-xs text-fg-subtle"
                >
                  🚇 {t}
                </span>
              ))}
            </div>
          )}
          {nearby.length > 0 && (
            <div className="flex flex-wrap gap-1.5">
              {nearby.slice(0, 6).map((n) => (
                <span
                  key={n}
                  className="inline-flex items-center gap-1 rounded-full border border-border bg-bg-card px-2.5 py-1 text-xs text-fg-subtle"
                >
                  📍 {n}
                </span>
              ))}
            </div>
          )}
        </div>
      ) : (
        <p className="text-xs text-fg-muted">
          {enrichedAt
            ? "No places found nearby — try refreshing after pinning a more precise location."
            : "Places near your property will appear here automatically after saving location."}
        </p>
      )}
    </div>
  );
}

function LocationDialog({ draft, patch, mode, assetId, listingId }: SectionDialogProps) {
  // UX-294: ref into the City Select trigger so we can scroll the host back
  // up when they try to interact with the disabled street-address field
  // without realising city is required first.
  const cityFieldRef = useRef<HTMLDivElement | null>(null);
  function focusCityPicker() {
    const el = cityFieldRef.current;
    if (!el) return;
    el.scrollIntoView({ behavior: "smooth", block: "center" });
    // Brief highlight pulse so the host's eye lands on the right field.
    el.classList.add("ring-2", "ring-warning/60", "rounded-md");
    setTimeout(() => {
      el.classList.remove("ring-2", "ring-warning/60", "rounded-md");
    }, 1500);
  }
  const { data: rawCities } = useReferenceCities();
  // UX-83: pin Chiang Mai + Bangkok to the top (current platform focus), then alphabetical
  const PRIORITY = ["Chiang Mai", "Bangkok"];
  const cities = rawCities?.slice().sort((a, b) => {
    const ai = PRIORITY.indexOf(a.name.en);
    const bi = PRIORITY.indexOf(b.name.en);
    if (ai !== -1 && bi !== -1) return ai - bi;
    if (ai !== -1) return -1;
    if (bi !== -1) return 1;
    return a.name.en.localeCompare(b.name.en);
  });
  const city = cities?.find((c) => c.id === draft.cityId);
  const lat = draft.latitude ?? city?.latitude ?? 13.7563;
  const lng = draft.longitude ?? city?.longitude ?? 100.5018;

  // UX-310: a standalone house has no "unit number" — relabel the field per
  // property style so the host knows what to type.
  const { data: refs } = useReferences();
  const cat = (refs?.propertyCategories ?? []).find((c) => c.id === draft.propertyCategoryId);
  const catKey = (cat?.code ?? (typeof cat?.name === "string" ? cat?.name : cat?.name?.en) ?? "").toLowerCase();
  const isHouse = /(house|villa|townhouse|cottage|bungalow)/.test(catKey);

  // ── Street address autocomplete (Nominatim, city-biased) ────────────────
  const [searchQuery, setSearchQuery] = useState(draft.streetAddress);
  const [results, setResults] = useState<NominatimResult[]>([]);
  const [searching, setSearching] = useState(false);
  const [showResults, setShowResults] = useState(false);
  // UX-254: warning when Nominatim returns a postal code from the wrong
  // province (mismatched against the selected city's expected prefix).
  const [postcodeWarning, setPostcodeWarning] = useState<string | null>(null);
  // Suppresses the next debounce-driven search — used when we set the input
  // value programmatically (city change, suggestion picked).
  const suppressNext = useRef(false);
  // Only search when the user has explicitly typed — prevents firing Nominatim
  // on open when the field is pre-filled (BUG-autocomplete-on-open).
  const userHasTyped = useRef(false);
  const lastSeq = useRef(0);

  useEffect(() => {
    if (!userHasTyped.current) return;
    if (suppressNext.current) {
      suppressNext.current = false;
      return;
    }
    if (!city) return;
    const q = searchQuery.trim();
    if (q.length < 3) {
      // eslint-disable-next-line react-hooks/set-state-in-effect
      setResults([]);
      return;
    }
    const seq = ++lastSeq.current;
    setSearching(true);
    const t = setTimeout(async () => {
      try {
        // city coords are optional on the reference DTO — fall back to the
        // Bangkok centroid so the viewbox is always numeric. (Inline literals
        // rather than the outer lat/lng so this effect keeps its dep array.)
        const cLng = city.longitude ?? 100.5018;
        const cLat = city.latitude ?? 13.7563;
        const vb = [
          cLng - CITY_RADIUS,
          cLat + CITY_RADIUS,
          cLng + CITY_RADIUS,
          cLat - CITY_RADIUS,
        ].join(",");
        const url = `https://nominatim.openstreetmap.org/search?format=json&q=${encodeURIComponent(
          q,
        )}&addressdetails=1&limit=8&viewbox=${vb}&bounded=1`;
        const resp = await fetch(url, {
          headers: { "Accept-Language": "en" },
        });
        if (seq !== lastSeq.current) return;
        const data: NominatimResult[] = await resp.json();
        setResults(data);
        setShowResults(true);
      } catch {
        /* network failed — leave results empty, user can pick on map */
      } finally {
        if (seq === lastSeq.current) setSearching(false);
      }
    }, 350);
    return () => clearTimeout(t);
  }, [searchQuery, city]);

  // UX-254: when Nominatim returns a postcode whose 2-digit prefix doesn't
  // match the selected city's province (e.g. 55xxx in Chiang Mai), prefer
  // keeping the existing draft.zipCode rather than overwriting with a wrong
  // value. Always returns the value to use; warning is rendered separately.
  function reconcilePostcode(geocoded: string | undefined, existingZip: string, cityName: string | undefined): string {
    if (!geocoded) return existingZip;
    const expectedPrefix = cityName ? CITY_POSTAL_PREFIX[cityName] : undefined;
    if (!expectedPrefix) return geocoded;
    if (geocoded.startsWith(expectedPrefix)) return geocoded;
    // Don't replace existing if geocoded looks wrong for this city.
    return existingZip || geocoded;
  }

  function applyAddressParts(parts: AddressParts, opts: { fromCoordinates: boolean; lat?: number; lng?: number }) {
    // BUG-364: reverse-geocode can land the same value in both Road and Soi —
    // typically when the only street component Nominatim returns is a "Soi …"
    // lane and the street fallback (display_name's first segment) re-uses it.
    // Don't write the duplicate into both structured fields; keep it as the Soi
    // when it looks like one, otherwise as the Road, and clear the other.
    let road = (parts.street ?? "").trim();
    let soi = (parts.soi ?? "").trim();
    if (road && soi && road.toLowerCase() === soi.toLowerCase()) {
      if (/^soi\b/i.test(soi)) road = "";
      else soi = "";
    }
    const street = road || soi || parts.subdistrict || parts.district;
    const expectedPrefix = city?.name?.en ? CITY_POSTAL_PREFIX[city.name.en] : undefined;
    const postcode = reconcilePostcode(parts.postcode, draft.zipCode, city?.name?.en);
    const next: Partial<typeof draft> = {
      streetAddress: street,
      street: road,
      soi,
      subdistrict: parts.subdistrict,
      district: parts.district,
      province: parts.province,
      zipCode: postcode,
    };
    if (opts.fromCoordinates && opts.lat !== undefined && opts.lng !== undefined) {
      next.latitude = opts.lat;
      next.longitude = opts.lng;
    }
    // Auto-fill Legal address only while the host hasn't customised it.
    if (!draft.legalAddressTouched) {
      next.legalAddress = composeLegalAddress({
        unitNumber: draft.unitNumber,
        street: road,
        soi,
        subdistrict: parts.subdistrict,
        district: parts.district,
        province: parts.province,
        postcode,
      });
    }
    patch(next);
    if (expectedPrefix && parts.postcode && !parts.postcode.startsWith(expectedPrefix)) {
      setPostcodeWarning(`Geocoded postal ${parts.postcode} doesn't match ${city?.name?.en}. Please double-check.`);
    } else {
      setPostcodeWarning(null);
    }
  }

  async function pickResult(r: NominatimResult) {
    const la = parseFloat(r.lat);
    const ln = parseFloat(r.lon);
    const parts = parseNominatim(r.address);
    const street = parts.street || r.display_name.split(",")[0]?.trim() || "";
    suppressNext.current = true;
    setSearchQuery(street);
    setShowResults(false);
    // BUG-326: Nominatim *search* results — especially named POIs like
    // "Sansai Country Ville" — frequently omit the `postcode` that *reverse*
    // geocoding on the very same point returns. That's why Postal code stopped
    // auto-filling on suggestion pick (the map-pin path already uses /reverse
    // and gets it). When the picked suggestion has no postcode, do a one-shot
    // reverse lookup on its coordinates to recover it. Graceful: on any
    // failure we just apply whatever the suggestion gave us.
    let resolved = parts;
    if (!parts.postcode && !Number.isNaN(la) && !Number.isNaN(ln)) {
      try {
        const resp = await fetch(
          `https://nominatim.openstreetmap.org/reverse?format=json&lat=${la}&lon=${ln}&addressdetails=1`,
          { headers: { "Accept-Language": "en" } },
        );
        const data = await resp.json();
        const rev = parseNominatim(data.address);
        if (rev.postcode) resolved = { ...parts, postcode: rev.postcode };
      } catch {
        /* reverse lookup failed — fall through with the suggestion's data */
      }
    }
    applyAddressParts({ ...resolved, street }, { fromCoordinates: true, lat: la, lng: ln });
  }

  return (
    <div>
      <div ref={cityFieldRef}>
        <Field label="City" required>
          <Select
            value={draft.cityId ? String(draft.cityId) : ""}
            onValueChange={(v) => {
              const cid = Number(v);
              const picked = cities?.find((c) => c.id === cid);
              const next: Partial<typeof draft> = { cityId: cid };
              // UX-339: pre-fill Province from the city name when it's still
              // empty (Chiang Mai / Bangkok / Phuket / Krabi share the name
              // with their province). Editable — the host can correct the few
              // cities whose province differs (e.g. Pattaya → Chonburi).
              if (picked && draft.province.trim() === "") {
                next.province = picked.name.en;
                if (!draft.legalAddressTouched) {
                  next.legalAddress = composeLegalAddress(legalPartsFor(draft, { province: picked.name.en }));
                }
              }
              patch(next);
            }}
          >
            <SelectTrigger>
              <SelectValue placeholder="Select city" />
            </SelectTrigger>
            {/* @ts-ignore — onOpenAutoFocus is a valid Radix prop at runtime (UX-82) */}
            <SelectContent onOpenAutoFocus={(e: Event) => e.preventDefault()}>
              {(cities ?? []).map((c) => (
                <SelectItem key={c.id} value={String(c.id)}>
                  {c.name.en}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </Field>
      </div>

      {/* Search-as-you-type street address. Disabled until city is set so we
          always have a search bias. UX-294: when disabled, an overlay
          captures clicks and scrolls back up to the City picker so the
          host doesn't get stuck wondering where the picker is. */}
      {/* UX-332: this is a search helper, not a stored field — calling it
          "Street address" made hosts think it was a second address to fill
          alongside "Legal address". Rename + reword so it's clearly just a
          way to find the spot and drop the pin; the address that's actually
          saved is the structured fields + Legal address below. */}
      <Field
        label="Find your address"
        hint={
          city
            ? "Search by name or street — we'll drop the map pin and fill the address fields below for you."
            : "↑ Select a city above to enable address search — tap the field to jump up."
        }
      >
        <div className="relative">
          <div className="relative">
            <MapPin
              size={14}
              className="absolute left-3 top-1/2 -translate-y-1/2 text-fg-subtle pointer-events-none"
            />
            <Input
              value={searchQuery}
              disabled={!city}
              onChange={(e) => {
                userHasTyped.current = true;
                setSearchQuery(e.target.value);
                // Push raw text into draft so closing the dialog doesn't lose it.
                patch({ streetAddress: e.target.value });
              }}
              onFocus={() => setShowResults(true)}
              onBlur={() => setTimeout(() => setShowResults(false), 150)}
              placeholder={city ? `e.g. 123 ${city.name.en} Rd` : "e.g. 123 Main Rd"}
              className="pl-9 pr-9"
              autoComplete="off"
            />
            {!city && (
              // Click-capture overlay: disabled <input> swallows clicks
              // silently, so we layer a button on top that does the scroll.
              <button
                type="button"
                onClick={focusCityPicker}
                aria-label="Pick a city first"
                className="absolute inset-0 cursor-pointer rounded-md"
              />
            )}
            {searching && (
              <Loader2
                size={14}
                className="absolute right-3 top-1/2 -translate-y-1/2 text-fg-subtle animate-spin"
              />
            )}
          </div>
          {showResults && !searching && results.length === 0 && searchQuery.trim().length >= 3 && (
            <div className="absolute z-30 left-0 right-0 top-[calc(100%+4px)] bg-bg-card border border-border rounded-xl shadow-lg overflow-hidden">
              <p className="px-4 py-3 text-sm text-fg-muted">No results — try a different address or pin on map</p>
            </div>
          )}
          {showResults && results.length > 0 && (
            <div className="absolute z-30 left-0 right-0 top-[calc(100%+4px)] bg-bg-card border border-border rounded-xl shadow-lg overflow-hidden max-h-72 overflow-y-auto">
              {results.map((r) => (
                <button
                  key={r.place_id}
                  type="button"
                  onMouseDown={(e) => {
                    e.preventDefault();
                    pickResult(r);
                  }}
                  className={cn(
                    "w-full text-left px-4 py-2.5 text-sm text-fg hover:bg-bg-subtle transition-colors flex items-start gap-2 border-b border-border last:border-b-0",
                  )}
                >
                  <MapPin size={14} className="text-fg-subtle shrink-0 mt-0.5" />
                  <span className="line-clamp-2 leading-snug">{r.display_name}</span>
                </button>
              ))}
            </div>
          )}
        </div>
        {city && searchQuery.trim().length >= 3 && (draft.latitude === null || draft.longitude === null) && !searching && (
          <p className="mt-2 text-xs text-warning flex items-start gap-1.5">
            <MapPin size={12} className="shrink-0 mt-0.5" />
            <span>Pick a suggestion above or tap the map below to confirm coordinates — we need a precise pin to publish.</span>
          </p>
        )}
      </Field>

      {/* UX-333: the map pin (coordinates) is the real gate for this section —
          mark it required so the indicator sits next to the actual blocker,
          not only on the text fields. */}
      <Field
        label="Pin on map"
        required
        hint={
          draft.latitude === null || draft.longitude === null
            ? "Required — pick a suggestion above or tap the map to drop the pin so we can place your listing."
            : "Tap the map to fine-tune the pin."
        }
      >
        <div className="h-48 rounded-xl overflow-hidden border border-border isolate">
          <Suspense fallback={<div className="h-full bg-bg-subtle animate-pulse" />}>
            <LocationPicker
              lat={lat}
              lng={lng}
              zoom={draft.latitude ? 16 : 11}
              onChange={async (la, ln) => {
                patch({ latitude: la, longitude: ln });
                // BUG-355: dropping or moving the pin is an explicit request to
                // (re)locate, so re-fill the structured address fields from the
                // new point — even if the search box already had text. The old
                // guard (`streetAddress non-empty → skip`) meant that after
                // searching "Pa Daet" once and then nudging the pin, the
                // Road/Soi/Subdistrict/Postal fields went stale. The host's
                // manually-edited Legal address is still protected separately by
                // `legalAddressTouched` inside applyAddressParts.
                try {
                  const resp = await fetch(
                    `https://nominatim.openstreetmap.org/reverse?format=json&lat=${la}&lon=${ln}&addressdetails=1`,
                    { headers: { "Accept-Language": "en" } },
                  );
                  const data = await resp.json();
                  const parts = parseNominatim(data.address);
                  const street = parts.street || data.display_name?.split(",")[0]?.trim() || "";
                  suppressNext.current = true;
                  setSearchQuery(street);
                  applyAddressParts({ ...parts, street }, { fromCoordinates: false });
                } catch {
                  /* reverse geocode failed — coordinates still saved */
                }
              }}
            />
          </Suspense>
        </div>
      </Field>

      <Row cols={2}>
        {/* UX-310: context-aware. A condo/apartment has a unit number; a
            standalone house has a house/plot number. Label + placeholder +
            helper switch so the host isn't left guessing what to type. */}
        <Field
          label={isHouse ? "House number" : "Unit / room number"}
          optional
          hint={isHouse ? "House or plot no., e.g. 88/7" : "Apartment / room no., e.g. A-1204"}
        >
          <Input
            value={draft.unitNumber}
            onChange={(e) => {
              const v = e.target.value;
              const nextPatch: Partial<typeof draft> = { unitNumber: v };
              if (!draft.legalAddressTouched) {
                nextPatch.legalAddress = composeLegalAddress(legalPartsFor(draft, { unitNumber: v }));
              }
              patch(nextPatch);
            }}
            placeholder={isHouse ? "88/7" : "A-1204"}
          />
        </Field>
        <Field label="Postal code" required>
          {/* BUG-80: select-all on focus so autocomplete-filled value is fully replaced on re-type */}
          <Input
            value={draft.zipCode}
            onChange={(e) => {
              patch({ zipCode: e.target.value });
              setPostcodeWarning(null);
            }}
            onFocus={(e) => e.target.select()}
            placeholder={city?.name?.en === "Chiang Mai" ? "50xxx" : "10xxx"}
            autoComplete="postal-code"
            className={cn(postcodeWarning && "border-warning")}
          />
          {postcodeWarning && (
            <p className="mt-1.5 text-xs text-warning flex items-start gap-1.5">
              <MapPin size={12} className="shrink-0 mt-0.5" />
              <span>{postcodeWarning}</span>
            </p>
          )}
        </Field>
      </Row>

      {/* UX-254 / UX-310: Structured Thai address fields. Auto-filled by
          Nominatim on map pin / search pick — host can override anything.
          Flattened out of a nested <Field> wrapper (which double-indented and
          made the inputs look like they "jumped") into a plain sub-heading so
          every row aligns with the Unit/Postal row above. */}
      <div className="mb-2 mt-1">
        <p className="text-sm font-semibold text-fg">Structured address</p>
        <p className="text-xs text-fg-muted mt-0.5">Pre-filled from the map pin — adjust if anything is off.</p>
      </div>
      <Row cols={2} className="mb-4">
        <Field label="Road / street name" optional hint="The main road, e.g. Chareonprathet Rd.">
          <Input
            value={draft.street}
            onChange={(e) => {
              const v = e.target.value;
              const nextPatch: Partial<typeof draft> = { street: v };
              if (!draft.legalAddressTouched) {
                nextPatch.legalAddress = composeLegalAddress(legalPartsFor(draft, { street: v }));
              }
              patch(nextPatch);
            }}
            placeholder="Chareonprathet Rd"
          />
        </Field>
        <Field label="Soi / Lane" optional hint="Side-lane off the main road (Thai “ซอย”). Leave blank if none.">
          <Input
            value={draft.soi}
            onChange={(e) => {
              const v = e.target.value;
              const nextPatch: Partial<typeof draft> = { soi: v };
              if (!draft.legalAddressTouched) {
                nextPatch.legalAddress = composeLegalAddress(legalPartsFor(draft, { soi: v }));
              }
              patch(nextPatch);
            }}
            placeholder="Soi 9"
          />
        </Field>
      </Row>
      <Row cols={3}>
          {/* UX-295: Tambon/Amphoe are Thai jargon — surface a one-liner so
              expat hosts know what to type instead of guessing. UX-296:
              Subdistrict/District/Province are functionally needed for the
              tenant-side district filter; flagging them as "optional but
              recommended" so hosts don't unintentionally remove themselves
              from neighbourhood searches. */}
          <Field
            label="Subdistrict"
            recommended
            hint="Tambon — usually filled automatically from the map pin. Tenants filter by it."
          >
            <Input
              value={draft.subdistrict}
              onChange={(e) => {
                const v = e.target.value;
                const nextPatch: Partial<typeof draft> = { subdistrict: v };
                if (!draft.legalAddressTouched) {
                  nextPatch.legalAddress = composeLegalAddress(legalPartsFor(draft, { subdistrict: v }));
                }
                patch(nextPatch);
              }}
              placeholder="Hai Ya"
            />
          </Field>
          <Field
            label="District"
            recommended
            hint="Amphoe (e.g. Mueang Chiang Mai). Without it your listing won't show in district searches."
          >
            <Input
              value={draft.district}
              onChange={(e) => {
                const v = e.target.value;
                const nextPatch: Partial<typeof draft> = { district: v };
                if (!draft.legalAddressTouched) {
                  nextPatch.legalAddress = composeLegalAddress(legalPartsFor(draft, { district: v }));
                }
                patch(nextPatch);
              }}
              placeholder="Mueang Chiang Mai"
            />
          </Field>
          <Field label="Province" recommended hint="Changwat — the province your listing sits in.">
            <Input
              value={draft.province}
              onChange={(e) => {
                const v = e.target.value;
                const nextPatch: Partial<typeof draft> = { province: v };
                if (!draft.legalAddressTouched) {
                  nextPatch.legalAddress = composeLegalAddress(legalPartsFor(draft, { province: v }));
                }
                patch(nextPatch);
              }}
              placeholder="Chiang Mai"
            />
          </Field>
        </Row>

      {/* UX-332: explain WHY this is the required one — it's the full address
          printed on the rental contract and TM-30 filing, so it can't be left
          blank, unlike the optional search/structured helpers above. */}
      <Field
        label="Full address (for the contract)"
        required
        hint={
          draft.legalAddressTouched
            ? "This goes on the rental contract & TM-30 filing. Manually edited — won't be auto-rewritten when you adjust the fields above. Clear it to re-enable autogeneration."
            : "This full address is printed on the rental contract & TM-30 filing — required. Autogenerated from the fields above; edit it to take manual control."
        }
      >
        <Textarea
          value={draft.legalAddress}
          onChange={(e) => patch({ legalAddress: e.target.value, legalAddressTouched: e.target.value.trim().length > 0 })}
          rows={3}
        />
      </Field>

      <Field label="Google Maps URL" optional>
        <Input
          value={draft.googleMapsUrl}
          onChange={(e) => patch({ googleMapsUrl: e.target.value })}
          placeholder="https://maps.app.goo.gl/…"
        />
      </Field>

      {mode === "edit" && assetId && listingId && (
        <NearbyStatus assetId={assetId} listingId={listingId} />
      )}
    </div>
  );
}

export const locationSection: SectionDef = {
  id: "location",
  label: "Address & location",
  group: "basics",
  required: true,
  estTime: "1 min",
  isComplete: (d) =>
    d.cityId !== null &&
    d.latitude !== null &&
    d.longitude !== null &&
    d.zipCode.trim().length > 0 &&
    d.legalAddress.trim().length > 0,
  // UX-333: the genuine blocker is usually the map pin, not the "*" text
  // fields. When everything textual is filled but the pin isn't dropped, the
  // disabled Continue button should say so instead of "Fill required fields
  // (marked *)" — which points the host at fields they've already completed.
  blockedReason: (d) => {
    const textReady =
      d.cityId !== null && d.zipCode.trim().length > 0 && d.legalAddress.trim().length > 0;
    if (textReady && (d.latitude === null || d.longitude === null)) {
      return "Drop the pin on the map to set your location";
    }
    return null;
  },
  summary: (d) => {
    if (d.cityId === null) return "—";
    const street = d.streetAddress || "Pinned on map";
    return d.unitNumber ? `${street}, ${d.unitNumber}` : street;
  },
  Form: LocationDialog,
};
